### ISSUE TITLE
Fish or cut bait with experimental

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#272]
What's the status on all these experimental packages? They should be resolved one way or the other, either merged into non-experimental or shifted to a different branch.

**Comment by loosebazooka** [comment]
I believe this is fixed now.

**Comment by elharo** [comment]
I still see experimental packages. If we're not going to proceed with these, let's delete them.

**Comment by loosebazooka** [comment]
Oh I thought this was about the tests failing. Sorry. Let's leave open for
now.

**Comment by elharo** [comment]
Ping. These don't seem to be on the main track of development. Should we delete them?

**Comment by elharo** [comment]
Checked in with @loosebazooka We agreed that this will either be released (i.e. no longer experimental) or deleted in 6 months. That is, 2017-11-05
